#! /usr/bin/perl

use warnings;
use strict;
use lib '../lib';

use chain;

chain::main::GenesisBlock(); print "ok\n";
chain::testnet::GenesisBlock(); print "ok\n";
chain::regtest::GenesisBlock(); print "ok\n";
