#! /usr/bin/perl -l

use warnings;
use strict;
use lib '../lib';

use data;

chdir '..' or die $!;

data::init ();

print "ok" if data::tx_exists (scalar reverse pack 'H*',
'd5d27987d2a3dfc724e359870c6644b40e497bdc0589a033220fe15429d88599');

print data::version ();

print join '*', map { unpack 'H*', reverse } data::blk_orphan (
scalar reverse pack 'H*',
'000000000000961f26a4c14a6745d1362d03c5eafeaa0d66138b000e5ca20b8c');
